FROM tutum/jboss:as7
#ADD /var/lib/jenkins/workspace/ticket-monster_2.7.0/demo/target/ticket-monster.war /jboss-as-7.1.1.Final/standalone/deployments/
ADD ticket-monster.war /jboss-as-7.1.1.Final/standalone/deployments/
EXPOSE 8080
