FROM tomcat
MAINTAINER info.inspectit@novatec-gmbh.de

# set Workdir
WORKDIR /opt

# set insepctit env
ENV INSPECTIT_AGENT_HOME /opt/agent
ENV INSPECTIT_CONFIG_HOME /opt/agent/active-config


# Add Sample App to hot deployment directory
COPY hello2.war /usr/local/tomcat/webapps/

# adding fresh agent from jenkins workspace
COPY ${WORKSPACE}/inspectIT/agent/inspectit-agent-sun1.5.zip /opt/

# unzip Agent, clean up .zip-file and set inspectit jvm options
RUN unzip inspectit-agent-sun1.5.zip \
&& rm -f inspectit-agent-sun1.5.zip \
&& sed -i '250i\'"export INSPECTIT_JAVA_OPTS=\"-Xbootclasspath/p:${INSPECTIT_AGENT_HOME}/inspectit-agent.jar -javaagent:${INSPECTIT_AGENT_HOME}/inspectit-agent.jar -Dinspectit.config=${INSPECTIT_CONFIG_HOME}\"" /usr/local/tomcat/bin/catalina.sh \
&& sed -i '251i\'"export JAVA_OPTS=\"\${INSPECTIT_JAVA_OPTS} \${JAVA_OPTS}\"" /usr/local/tomcat/bin/catalina.sh

# copy start script and agent config
COPY runscripts/run-tomcat-with-inspectit.sh /run-tomcat-with-inspectit.sh

# define default command for container startup
CMD ["/run-tomcat-with-inspectit.sh", "run"]
